Repository IATI/IATI-Standard-Website, pull requests merged in 2018-05, with the labels that each got.

#95 Alpha refactor people
  iati/about/templates/about/people_page.html
  iati/iati/static/assets/svg/source/logo-square.svg
Labels: complete, enhancement

#96 Test default page generation
  .gitignore
  README.md
  iati/conftest.py
  iati/iati/settings/local.py.example
  iati/tests/functional_tests.py
Labels: complete, enhancement, incomplete

#68 sub-sub page sidepanel styling and new css
  iati/home/templates/home/includes/sidepanel.html
  iati/home/templatetags/iati_tags.py
Labels: complete, enhancement

#100 No none excerpt
  iati/about/templates/about/about_page.html
  iati/about/templates/about/about_sub_page.html
  iati/about/templates/about/case_study_index_page.html
  iati/about/templates/about/case_study_page.html
  iati/about/templates/about/history_page.html
  iati/about/templates/about/people_page.html
Labels: complete, enhancement

#101 Fix index link
  iati/about/templates/about/case_study_index_page.html
Labels: complete, enhancement

#99 Setup functional test files
  iati/tests/about_functional_tests.py
  iati/tests/base_functional_tests.py
  iati/tests/contact_functional_tests.py
  iati/tests/events_functional_tests.py
  iati/tests/home_functional_tests.py
  iati/tests/news_functional_tests.py
  iati/tests/support_functional_tests.py
Labels: complete, enhancement

#102 Alpha banner
  iati/iati/templates/base.html
Labels: complete, enhancement

#103 Fixes some linting errors and adds basic default page test
  .gitignore
  iati/tests/base_functional_tests.py
  iati/tests/data/strings.py
  iati/tests/functional_tests.py
Labels: complete, enhancement

#69 Refactor people
  iati/about/models.py
  iati/about/templates/about/people_page.html
  iati/iati/static/assets/svg/source/logo-square.svg
Labels: enhancement, incomplete

#104 Test about sub page live server
  iati/conftest.py
  iati/home/templatetags/iati_tags.py
  iati/iati/settings/base.py
  iati/search/migrations/0001_initial.py
  iati/search/migrations/__init__.py
  iati/tests/about_functional_tests.py
  iati/tests/base_functional_tests.py
  iati/tests/functional_tests.py
Labels: complete, enhancement

#13 Add about models
  iati/about/models.py
  iati/about/templates/about/about_page.html
  iati/about/templates/about/about_sub_page.html
  iati/about/templates/about/case_study_index_page.html
  iati/about/templates/about/case_study_page.html
  iati/about/templates/about/download_listing_page.html
  iati/about/templates/about/history_page.html
  iati/about/templates/about/people_page.html
  iati/about/translation.py
  iati/events/models.py
  iati/guidance_and_support/models.py
  iati/home/migrations/0003_about.py
  iati/home/migrations/0004_auto_20180329_1351.py
  iati/home/models.py
  iati/home/templates/home/includes/download_box.html
  iati/home/templates/home/includes/sibling_links.html
  iati/iati/static/assets/img/image-placeholder.svg
  iati/iati/static/assets/svg/source/logo-square.svg
  iati/news/models.py
Labels: complete, enhancement

#105 Test about sub page
  README.md
  iati/conftest.py
  iati/home/templatetags/iati_tags.py
  iati/iati/settings/base.py
  iati/search/migrations/0001_initial.py
  iati/search/migrations/__init__.py
  iati/tests/about_functional_tests.py
  iati/tests/base_functional_tests.py
  iati/tests/functional_tests.py
Labels: complete, enhancement

#107 Test case study children
  iati/tests/about_functional_tests.py
Labels: complete, enhancement

#106 Refactor createdefaultpages
  iati/home/management/commands/createdefaultpages.py
  iati/tests/base_functional_tests.py
Labels: complete, enhancement

#109 Refactor to make sure admin CMS window closes, update docstring
  iati/tests/about_functional_tests.py
Labels: bug, complete

#112 Remove test that throws Splinter error
  iati/tests/functional_tests.py
Labels: bug, complete

#111 Guidance models alpha
  iati/guidance_and_support/models.py
  iati/guidance_and_support/templates/guidance_and_support/guidance_and_support_page.html
  iati/guidance_and_support/templates/guidance_and_support/guidance_index_page.html
  iati/guidance_and_support/templates/guidance_and_support/guidance_page.html
  iati/guidance_and_support/translation.py
  iati/iati/templates/base.html
Labels: enhancement, incomplete

#108 Setup travis to run test commands
  .travis.yml
  Makefile
  README.md
  iati/tests/test_sample.py
  setup.cfg
Labels: complete, enhancement

#116 Fix setup commands in README
  README.md
Labels: complete, documentation

#115 Run django/wagtail functional tests on Travis
  .pylintrc
  .travis.yml
  Makefile
  README.md
  iati/__init__.py
  iati/about/tests.py
  iati/contact/tests.py
  iati/events/tests.py
  iati/guidance_and_support/tests.py
  iati/home/__init__.py
  iati/home/migrations/__init__.py
  iati/home/models.py
  iati/iati/__init__.py
  iati/iati/settings/__init__.py
  iati/iati/settings/base.py
  iati/iati/settings/dev.py
  iati/iati/settings/production.py
  iati/iati/urls.py
  iati/iati/wsgi.py
  iati/manage.py
  iati/news/tests.py
  iati/requirements_dev.txt
  iati/search/__init__.py
  iati/search/views.py
  iati/tests/conftest.py
  setup.cfg
Labels: enhancement, incomplete

#119 Add link to current Privacy Policy
  iati/iati/templates/base.html
Labels: complete, enhancement

#121 Set DJANGO_SETTINGS_MODULE in pytest settings
  .travis.yml
  pytest.ini
Labels: complete, enhancement

#75 Add new pagination style
  iati/home/templates/home/includes/pagination_links.html
Labels: complete, enhancement

#123 New CSS adds headers and new image classes
  iati/iati/static/assets/css/screen.css
Labels: complete, enhancement

#125 Pins dependcies to specific versions
  iati/requirements.txt
Labels: complete, enhancement

#126 Download django-modeltranslation==0.13b1 from pip
  iati/requirements.txt
Labels: complete, enhancement

#131 Editable home header text
  iati/home/models.py
  iati/home/templates/home/includes/hero_heading.html
  iati/home/translation.py
  iati/tests/home_functional_tests.py
Labels: complete, enhancement
