Repository IATI/IATI-Standard-Website, pull requests merged in 2018-09, with the labels that each got.

#246 Modeltranslation sync
  iati/events/templates/events/event_index_page.html
  iati/events/templates/events/event_page.html
  iati/guidance_and_support/templates/guidance_and_support/guidance_group_page.html
  iati/guidance_and_support/templates/guidance_and_support/guidance_page.html
  iati/home/templates/home/home_page.html
  iati/home/templates/home/includes/featured_event.html
  iati/home/templates/home/includes/pagination_links.html
  iati/home/templates/home/includes/sibling_links.html
  iati/home/templates/home/includes/sidepanel.html
  iati/home/templates/home/includes/translation_links.html
  iati/home/templatetags/iati_tags.py
  iati/iati/settings/base.py
  iati/iati_standard/templates/iati_standard/iati_standard_page.html
  iati/modeltranslation_sync/__init__.py
  iati/modeltranslation_sync/management/__init__.py
  iati/modeltranslation_sync/management/commands/__init__.py
  iati/modeltranslation_sync/management/commands/load_trans.py
  iati/modeltranslation_sync/management/commands/save_trans.py
  iati/news/templates/news/news_index_page.html
  iati/news/templates/news/news_page.html
  iati/requirements.txt
  iati/tests/events_functional_tests.py
Labels: complete, enhancement

#247 Dev to master for modeltranslation_sync
  iati/events/templates/events/event_index_page.html
  iati/events/templates/events/event_page.html
  iati/guidance_and_support/templates/guidance_and_support/guidance_group_page.html
  iati/guidance_and_support/templates/guidance_and_support/guidance_page.html
  iati/home/templates/home/home_page.html
  iati/home/templates/home/includes/featured_event.html
  iati/home/templates/home/includes/pagination_links.html
  iati/home/templates/home/includes/sibling_links.html
  iati/home/templates/home/includes/sidepanel.html
  iati/home/templates/home/includes/translation_links.html
  iati/home/templatetags/iati_tags.py
  iati/iati/settings/base.py
  iati/iati_standard/templates/iati_standard/iati_standard_page.html
  iati/modeltranslation_sync/__init__.py
  iati/modeltranslation_sync/management/__init__.py
  iati/modeltranslation_sync/management/commands/__init__.py
  iati/modeltranslation_sync/management/commands/load_trans.py
  iati/modeltranslation_sync/management/commands/save_trans.py
  iati/news/templates/news/news_index_page.html
  iati/news/templates/news/news_page.html
  iati/requirements.txt
  iati/tests/events_functional_tests.py
Labels: complete, enhancement

#250 No more quote, makes page too skinny
  iati/using_data/templates/using_data/using_data_page.html
Labels: complete, enhancement

#255 Add two missing closing divs
  iati/events/templates/events/event_page.html
Labels: Quick fix, complete, enhancement

#260 Dev to master for Event sort quickfix
  iati/events/models.py
Labels: Quick fix, complete, enhancement

#261 Featured event sort
  iati/events/migrations/0003_eventpage_featured_event.py
  iati/events/models.py
  iati/events/templates/events/event_index_page.html
Labels: enhancement

#265 Toolbox id
  iati/guidance_and_support/templates/guidance_and_support/guidance_page.html
  iati/guidance_and_support/templates/guidance_and_support/knowledgebase_index_page.html
  iati/guidance_and_support/templates/guidance_and_support/knowledgebase_page.html
  iati/using_data/templates/using_data/tools_index_page.html
Labels: Quick fix, complete, enhancement

#242 [Needs tests] Get search styled up and working
  iati/home/models.py
  iati/home/templates/home/includes/search_bar.html
  iati/iati/templates/base.html
  iati/search/templates/search/search.html
  iati/search/views.py
Labels: enhancement
