Repository IATI/IATI-Standard-Website, pull requests merged in 2018-10, with the labels that each got.

#272 Link publishers numbers to registry / activities numbers to d-portal
  iati/home/static/home/css/responsive.css
  iati/home/templates/home/home_page.html
Labels: enhancement, for IATI

#271 Fix slug trailing dash
  iati/home/models.py
  iati/tests/management_unit_tests.py
Labels: bug

#275 Django version upgraded from 2.0.5 to 2.0.8
  iati/requirements.txt
Labels: Quick fix
