Repository IATI/IATI-Standard-Website, pull requests merged in 2018-07, with the labels that each got.

#170 Additional news and events
  news2.json
Labels: complete, enhancement

#171 Working event reg button
  iati/events/templates/events/event_page.html
Labels: complete, enhancement

#172 Reference redirect
  iati/home/views.py
  iati/iati/urls.py
Labels: complete, enhancement

#173 Remove excerpt placeholder
  iati/about/templates/about/about_sub_page.html
  iati/about/templates/about/case_study_index_page.html
  iati/about/templates/about/case_study_page.html
  iati/about/templates/about/history_page.html
  iati/about/templates/about/people_page.html
  iati/home/templates/home/home_page.html
  iati/home/templates/home/includes/hero_heading.html
Labels: complete, enhancement

#188 Fix homepage links
  iati/home/templates/home/home_page.html
  iati/iati/templates/base.html
Labels: complete, enhancement

#190 Update iati video on the homepage
  iati/home/templates/home/home_page.html
Labels: complete, enhancement

#196 All publishers fix
  iati/home/management/commands/updatestatistics.py
Labels: complete, enhancement

#201 [COMPLETE] More linting fixes
  .pylintrc
  .travis.yml
  iati/contact/models.py
  iati/events/models.py
  iati/events/translation.py
  iati/guidance_and_support/models.py
  iati/home/management/commands/importnews.py
  iati/home/management/commands/updatestatistics.py
  iati/home/templatetags/iati_tags.py
  iati/home/wagtail_hooks.py
  iati/iati/activate_languages.py
  iati/iati/urls.py
  iati/iati_standard/models.py
  iati/news/models.py
  iati/news/translation.py
  iati/tests/home_functional_tests.py
  iati/using_data/translation.py
Labels: enhancement, incomplete

#200 Add DOM IDs to h2 tags that contain number of activities/organisations
  iati/home/templates/home/home_page.html
Labels: complete, enhancement

#210 Remove foot comment containing emails
  iati/iati/templates/base.html
Labels: Quick fix, complete, enhancement

#213 Dev
  iati/iati/templates/base.html
Labels: Quick fix, complete, enhancement

#214 Fix broken redirects (currently returning a server error)
  iati/iati/urls.py
  iati/iati_standard/templates/iati_standard/iati_standard_page.html
Labels: Quick fix, complete, enhancement

#218 Dev to master
  iati/iati/urls.py
  iati/iati_standard/templates/iati_standard/iati_standard_page.html
Labels: Quick fix, bug, complete

#220 Merge dev into master
  .travis.yml
Labels: complete, enhancement

#222 Update readme
  README.md
Labels: complete, documentation, enhancement

#223 Merge dev into master
  README.md
Labels: complete, documentation, enhancement
