Repository IATI/IATI-Standard-Website, pull requests merged in 2018-04, with the labels that each got.

#8 Remove migrations merge
  .gitignore
  iati/home/migrations/0001_initial.py
  iati/home/migrations/0002_create_homepage.py
  iati/home/migrations/__init__.py
Labels: complete

#7 Remove migrations and add dir to .gitignore to avoid merge problems
  .gitignore
  iati/home/migrations/0001_initial.py
  iati/home/migrations/0002_create_homepage.py
  iati/home/migrations/__init__.py
Labels: complete

#9 .gitattributes for prefering local file merges into migrations folder
  .gitattributes
Labels: complete, enhancement

#12 Allow different URL path redirects for localization
  iati/iati/settings/base.py
  iati/iati/settings/dev.py
  iati/iati/urls.py
Labels: complete, enhancement

#6 Add modeltranslation
  iati/about/translation.py
  iati/contact/translation.py
  iati/events/translation.py
  iati/guidance_and_support/translation.py
  iati/home/translation.py
  iati/iati/settings/base.py
  iati/news/translation.py
  iati/requirements.txt
Labels: complete, enhancement

#21 Add Splinter for functional testing
  iati/requirements_dev.txt
Labels: complete, enhancement

#23 Swap plain Splinter for the pytest-splinter plugin
  iati/requirements_dev.txt
Labels: complete, enhancement

#14 Add page templates
  iati/about/models.py
  iati/about/templates/about/about.html
  iati/about/templates/about/about_page.html
  iati/about/templates/about/about_sub_page.html
  iati/about/templates/about/case_study_page.html
  iati/about/templates/about/download_listing_page.html
  iati/about/templates/about/history_page.html
  iati/about/translation.py
  iati/contact/models.py
  iati/contact/templates/contact/contact_page.html
  iati/contact/translation.py
  iati/events/models.py
  iati/events/templates/events/event_index_page.html
  iati/events/templates/events/event_page.html
  iati/events/translation.py
  iati/guidance_and_support/models.py
  iati/guidance_and_support/translation.py
  iati/home/templatetags/iati_tags.py
  iati/news/models.py
  iati/news/templates/news/news_index_page.html
  iati/news/templates/news/news_page.html
  iati/news/translation.py
Labels: complete, enhancement

#37 Refactor test
  iati/home/templatetags/iati_tags.py
Labels: complete, enhancement

#35 Add default page command
  iati/about/migrations/0002_auto_20180410_1543.py
  iati/contact/migrations/0002_auto_20180410_1543.py
  iati/events/migrations/0005_auto_20180410_1543.py
  iati/events/templates/events/event_index_page.html
  iati/guidance_and_support/migrations/0002_auto_20180410_1543.py
  iati/home/management/__init__.py
  iati/home/management/commands/__init__.py
  iati/home/management/commands/createdefaultpages.py
  iati/home/templates/home/includes/translation_links.html
  iati/home/templatetags/iati_tags.py
  iati/iati/templates/base.html
  iati/news/migrations/0002_auto_20180410_1543.py
  iati/search/templates/search/search.html
Labels: complete, enhancement

#38 Translation helper
  iati/home/translation_helper.py
Labels: complete, enhancement

#40 tidy code a little bit and make the linters happier
  iati/home/management/commands/createdefaultpages.py
Labels: complete, enhancement

#43 Fix command in setup instructions
  README.md
Labels: complete, documentation

#41 Remove translationfield and add panels to homepage
  iati/home/models.py
  iati/home/translation.py
Labels: complete, enhancement

#42 Allow inline models in translation_helper
  iati/home/translation_helper.py
Labels: complete, enhancement

#44 Add additional setup commands
  README.md
Labels: complete, documentation

#47 We don't need this second save command, it forces the page into a dra…
  iati/home/management/commands/createdefaultpages.py
Labels: complete, enhancement

#45 Ignore media folder
  .gitignore
Labels: complete, enhancement

#48 Add fffunction html structure
  iati/home/image_formats.py
  iati/home/models.py
  iati/home/templates/home/includes/streamfield.html
Labels: complete, enhancement

#52 We forgot to move the stars
  iati/home/models.py
Labels: complete, enhancement

#54 Download box
  iati/home/templates/home/includes/download_box.html
Labels: complete, enhancement

#53 Pagination link template
  iati/home/templates/home/includes/pagination_links.html
Labels: complete, enhancement

#56 Fav ico
  iati/iati/static/assets/favicons/favicon-16x16.png
  iati/iati/static/assets/favicons/favicon-32x32.png
  iati/iati/static/assets/favicons/favicon.ico
  iati/iati/static/assets/svg/source/logo-icon.svg
  iati/iati/templates/base.html
Labels: complete, enhancement

#57 Move events-model iati_tag.py changes upstream
  iati/home/templates/home/includes/download_box.html
  iati/home/templatetags/iati_tags.py
Labels: complete, enhancement

#58 Can't use fields attribute from TranslationOptions
  iati/home/models.py
  iati/home/translation.py
  iati/home/translation_helper.py
Labels: complete, enhancement

#59 Abstract trans fields
  iati/home/models.py
Labels: complete, enhancement

#64 From en-gb to just en
  iati/iati/settings/base.py
Labels: complete, enhancement

#66 Remove unnecessary setup commands
  README.md
Labels: complete, documentation

#67 Combine download_listing_page with about_subpage
  iati/about/models.py
  iati/about/templates/about/about_sub_page.html
  iati/about/templates/about/download_listing_page.html
Labels: complete, enhancement

#70 Twitter link, but we don't have a Facebook or a LinkedIn?
  iati/iati/templates/base.html
Labels: complete, enhancement

#71 Static and dynamic error pages for wagtail and apache2
  iati/iati/templates/404-static.html
  iati/iati/templates/404.html
  iati/iati/templates/500-static.html
  iati/iati/templates/500.html
  iati/iati/templates/error-base.html
Labels: complete, enhancement

#73 Allow languages to be activated individually, regardless of languages…
  iati/home/templates/home/includes/translation_links.html
  iati/home/templatetags/iati_tags.py
  iati/iati/activate_languages.py
  iati/iati/settings/base.py
  iati/iati/urls.py
Labels: complete, enhancement

#85 New placeholder and new sibling links
  iati/about/templates/about/case_study_index_page.html
  iati/home/templates/home/includes/sibling_links.html
  iati/iati/static/assets/img/image-placeholder.svg
Labels: complete, enhancement

#90 Guidance and support templates
  iati/guidance_and_support/templates/guidance_and_support/guidance_and_support_page.html
  iati/guidance_and_support/templates/guidance_and_support/guidance_index_page.html
  iati/guidance_and_support/templates/guidance_and_support/guidance_page.html
  iati/guidance_and_support/templates/guidance_and_support/knowledgebase_index_page.html
  iati/guidance_and_support/templates/guidance_and_support/knowledgebase_page.html
  iati/iati/static/assets/css/screen.css
Labels: complete, enhancement

#92 Static content for guidance landing page
  iati/guidance_and_support/templates/guidance_and_support/guidance_and_support_page.html
  iati/iati/static/assets/css/screen.css
Labels: complete, enhancement
