Repository IATI/IATI-Standard-Website, pull requests merged in 2019-01, with the labels that each got.

#285 Fix Travis' current state
  .travis.yml
  Makefile
  iati/requirements_dev.txt
  iati/tests/home_functional_tests.py
Labels: bug, complete

#284 Updating the paginator to make it more interactive
  .pylintrc
  iati/about/models.py
  iati/events/models.py
  iati/home/models.py
  iati/home/static/home/css/custom.css
  iati/home/templates/home/includes/pagination_links.html
  iati/iati/templates/base.html
  iati/news/models.py
  iati/search/views.py
  iati/tests/events_functional_tests.py
Labels: enhancement

#287 Integrate Google Search in iatistandard.org
  iati/home/static/home/css/custom.css
  iati/home/templates/home/includes/search_bar.html
  iati/search/templates/search/search.html
Labels: enhancement, incomplete

#292 Feature/translation faq master
  iati/home/models.py
  iati/iati/templates/base.html
Labels: Quick fix, complete, enhancement
